### PR TITLE
fix: Fix generation on Windows

### LINKED ISSUE #154: Generation scripts fail on Windows
## Expected Behavior

Running `./scripts/gen.sh` on Windows should regenerate everything appropriately

## Actual Behavior

The schema is regenerated with very different content, and then there's a 

## Steps to Reproduce the Problem

- Start a Windows VM
- Install Go, Node and bash (simplest option for the latter is to use the bash that comes with Git for Windows)
- Clone this repo
- Run `./scripts/gen.sh` from bash and wait for the errors

Error seen:

```text
Error: ENOENT: no such file or directory, open 'C:\users\jonskeet\GitHub\googleapis\google-cloudevents\tools\readme-catalog/../../jsonschema/catalog.json'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.<anonymous> (C:\users\jonskeet\GitHub\googleapis\google-cloudevents\tools\readme-catalog\index.js:6:31)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\users\\jonskeet\\GitHub\\googleapis\\google-cloudevents\\tools\\readme-catalog/../../jsonschema/catalog.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

... but some part of the script had earlier *deleted* `jsonschema/catalog.json`. I don't know why yet - I haven't tried to debug it.

### PR DESCRIPTION
**Pull request by jskeet**
Fixes #154

### CODE REVIEW

**Comment by jskeet** [comment]
The other problems I was running into appear to be due to using an old version of the Chrusty plugin. The generation script attempts to specify which version to use, so I'm not quite sure what was going on there, but after removing every trace of it from my Go installation and rerunning, I got to "no changes".

File: tools/proto2jsonschema/postgen.js [hunk 1]
```diff
@@ -38,6 +38,11 @@ console.log(`Fixing paths in dir: ${ROOT}`);
     
     // Create the modified JSON schema output
     const json = JSON.parse(fs.readFileSync(filePath).toString());
+
+    // Replace backslashes with forward-slashes to allow the script
+    // to work on Windows.
+    filePath = filePath.replace(/\\/g, '/');
```
Comment (grant) [inline tools/proto2jsonschema/postgen.js:44]: Great.

I think we want to normalize the file path right when we get it.

Can we do the following:

```js
filePaths.map(filePath => {
  // Normalize path slashes (`/`, `\`) to allow the script to work on Windows.
  filePath = path.normalize(filePath);
```

This replace may work just as well if you prefer it.

https://nodejs.org/api/path.html#path_path_normalize_path

**Review by grant — CHANGES_REQUESTED** [review]
Thanks! 1 comment.

File: tools/proto2jsonschema/postgen.js (hunk 1 above)
Comment (jskeet) [reply tools/proto2jsonschema/postgen.js:44]: I'll give it a try.

Comment (jskeet) [reply tools/proto2jsonschema/postgen.js:44]: Nope, that doesn't work - because it still leaves backslashes as backslashes, and later code assumes it's got forward slashes. (Basically it normalizes to "the platform default", rather than normalizing to forward slashes.)

I suspect if we used path operations everywhere instead of using string operations, we'd be okay - but that would be a bigger change.

Comment (grant) [reply tools/proto2jsonschema/postgen.js:44]: Alright. I was hoping there's a way to fix the slashes without character replacements, but this seems fine.

**Review by grant — APPROVED** [review]
